//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string Manv { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
        public string ChucVu { get; set; }
        public Nullable<double> Luong { get; set; }
    }
}
